version: '3.3'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - ../PostgreSQL:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks: 
      - ai_network

  aeye_ai:
    build:
      dockerfile: AI/Dockerfile
    image: aeye_ai:1.0
    container_name: aeye_ai
    volumes:
      - ../app/:/app/
    ports:
      - "2000:2000"
    networks:
      - ai_network
    command: tail -f /dev/null
  
networks:
  ai_network:
    driver: bridge
